theme: jekyll-theme-minimal
title: HTML-Templates für YForm (REDAXO 5)
description: HTML-Templates für E-Mails auf YForm-Basis 
logo: https://raw.githubusercontent.com/alexplusde/email_templates/master/docs/screenshot.png
show_downloads: true
